<?php
/*
fulfillment server

Demo/tutorial for dialogflow.com
how to add/edit/delete and search 
when user entry data,data would stored in database mysql
when user view data,data would displayed from database mysql
when user delete data,data would trashed from database mysql
when user update data,data would updated in database mysql


+================================================+
+ code made by Kukuh TW                          +
+ email:kukuhtw@gmail.com , kukuhtw@kukuhtw.com  +
+ whatsapp : 62-812.9893.706                     + 
+ website: http://kukuhtw.com                    +
+ twitter: @kukuhtw                              + 
+================================================+

*/

//ini_set('display_errors', 1); //unset bila sedang debug
//ini_set('display_startup_errors', 1); //unset bila sedang debug
//error_reporting(E_ALL); //unset bila sedang debug

//database setting
include("db_crowhill.php");
//function
include("function_crowhill.php");

//setting zone time wilayah
date_default_timezone_set("Asia/Jakarta");
$tanggalhariini = date("Y/m/d");
$jamhariini = date("H:i:sa");
$saatini = $tanggalhariini. " ".$jamhariini;
//command to get content from dialogflow that forwarded to this server
$update_response = file_get_contents("php://input");
//data in JSON format and needs to decode
$update = json_decode($update_response, true);

//get parameter action that set in intents at agents dialogflow.com
$varresultaction = $update["queryResult"]["action"];
//get parameter session from agents dialogflow.com

//this is messages text
$messages = $update["queryResult"]["queryText"];
//this is session
$session = $update["session"];

//get variable search from JSON dialogflow
$search = (isset($update["queryResult"]["parameters"]["search"]) ? $update["queryResult"]["parameters"]["search"] : null);

//get variable id from JSON dialogflow
$id = (isset($update["queryResult"]["parameters"]["id"]) ? $update["queryResult"]["parameters"]["id"] : null);

//get variable standnumber from JSON dialogflow
$standnumber = (isset($update["queryResult"]["parameters"]["standnumber"]) ? $update["queryResult"]["parameters"]["standnumber"] : null);

$standsize = (isset($update["queryResult"]["parameters"]["standsize"]) ? $update["queryResult"]["parameters"]["standsize"] : null);

$firstname = (isset($update["queryResult"]["parameters"]["firstname"]) ? $update["queryResult"]["parameters"]["firstname"] : null);

$lastname = (isset($update["queryResult"]["parameters"]["lastname"]) ? $update["queryResult"]["parameters"]["lastname"] : null);

$phonenumber = (isset($update["queryResult"]["parameters"]["phonenumber"]) ? $update["queryResult"]["parameters"]["phonenumber"] : null);

$datepurchased = (isset($update["queryResult"]["parameters"]["datepurchased"]) ? $update["queryResult"]["parameters"]["datepurchased"] : null);
//eliminate value T12:00:00+07:00
$datepurchased=str_replace("T12:00:00+07:00","", $datepurchased);

$nationalid = (isset($update["queryResult"]["parameters"]["nationalid"]) ? $update["queryResult"]["parameters"]["nationalid"] : null);

/*
value parameter session woulde be:
$session="projects/[nama_title_agent]/agent/sessions/343363b-2166e-47d3b-c9371-f5e0e2a3";
we need this value `343363b-2166e-47d3b-c9371-f5e0e2a3` , store this value in parameter sessionunique
*/

$ignore1="";
$sessionunique="";

if ($session!="") {
	$list  = list($ignore1,$sessionunique) = explode('sessions/', $session);
}
else {
	//else if session is empty
		$nothinng="you dont have session"; 
		sendMessage(array(
            "source" => null,
           "fulfillmentText" => $nothinng
			));
		exit;
}

// when action == entry_data
if ($varresultaction=="entry_data") {
	//call function add_data and their-parameters,return lastID generated by mysql database
	$last_id = add_data($standnumber,$firstname,$lastname,
	$standsize,$datepurchased,$phonenumber,$nationalid,$saatini,$link,$mySQLserver,$mySQLdefaultdb,$mySQLuser,$mySQLpassword);
	$response="Data has been saved , dataID is ".$last_id;
	sendMessage(array(
            "source" => null,
           "fulfillmentText" => $response
			));
		exit;
}
if ($varresultaction=="view_data") {
	//if user would like to see all data,he/shewould type `all` 
	if ($id=="all") {
		$id="";
	}
	
	$response=view_data($id,$saatini,$link,$mySQLserver,$mySQLdefaultdb,$mySQLuser,$mySQLpassword);
	sendMessage(array(
            "source" => null,
           "fulfillmentText" => $response
			));
		exit;
}
//display current data based on ID, so user can edit/update
if ($varresultaction=="display_data_to_edit"){
	$response ="copy and paste form update below this \n\n";
	$response .=display_data_to_edit($id,$saatini,$link,$mySQLserver,$mySQLdefaultdb,$mySQLuser,$mySQLpassword);
	sendMessage(array(
            "source" => null,
           "fulfillmentText" => $response
			));
		exit;

}
//When user update/edit data
if ($varresultaction=="update_data"){
	$response= update_data($id,$standnumber,$firstname,$lastname,
	$standsize,$datepurchased,$phonenumber,$nationalid,$saatini,$link,$mySQLserver,$mySQLdefaultdb,$mySQLuser,$mySQLpassword);
	sendMessage(array(
            "source" => null,
           "fulfillmentText" => $response
			));
		exit;
}

//When user search data
if ($varresultaction=="search") {
	$response= search_data($search,$saatini,$link,$mySQLserver,$mySQLdefaultdb,$mySQLuser,$mySQLpassword);
	sendMessage(array(
            "source" => null,
           "fulfillmentText" => $response
			));
		exit;
}
//When user delete
if ($varresultaction=="delete") {
	$response=delete_data($id,$saatini,$link,$mySQLserver,$mySQLdefaultdb,$mySQLuser,$mySQLpassword);
	sendMessage(array(
            "source" => null,
           "fulfillmentText" => $response
			));
		exit;
}


	$response="nothing to say";
		sendMessage(array(
            "source" => null,
           "fulfillmentText" => $response
			));
		exit;
		
//========================= EOF ==================================
?>
